# Generated by Django 5.0.10 on 2025-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_version_accepted",
            field=models.CharField(
                blank=True,
                help_text="Version of Privacy Policy user accepted",
                max_length=20,
                verbose_name="privacy version accepted",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_version_accepted",
            field=models.CharField(
                blank=True,
                help_text="Version of Terms of Service user accepted",
                max_length=20,
                verbose_name="terms version accepted",
            ),
        ),
    ]
