# Generated by Django 6.0 on 2025-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_legal_version_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='is_used',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when token was used for password reset', null=True, verbose_name='used at'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token'),
        ),
    ]
