# Generated by Django 6.0 on 2025-12-07 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email address for OTP verification', max_length=254, verbose_name='email')),
                ('code_hash', models.CharField(help_text='SHA256 hash of the OTP code', max_length=128, verbose_name='code hash')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Date and time when the OTP expires', verbose_name='expires at')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts made', verbose_name='attempts')),
                ('used', models.BooleanField(db_index=True, default=False, help_text='Whether the OTP has been successfully used', verbose_name='used')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which OTP was requested', null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'OTP token',
                'verbose_name_plural': 'OTP tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'used', '-created_at'], name='accounts_ot_email_255680_idx')],
            },
        ),
    ]
