# Generated by Django 5.0.10 on 2025-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                        ],
                        help_text="Type of legal document",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text='Version number (e.g., "1.0", "2.0")',
                        max_length=20,
                        verbose_name="version",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title displayed to users",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="HTML content of the document", verbose_name="content"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this version becomes effective",
                        verbose_name="effective date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one document per type can be active. Activating this will deactivate others of the same type.",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal document",
                "verbose_name_plural": "legal documents",
                "ordering": ["-effective_date"],
                "unique_together": {("document_type", "version")},
            },
        ),
    ]
