# Generated by Django 6.0 on 2025-12-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_legal_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], db_index=True, help_text='Type of legal document', max_length=20, verbose_name='document type'),
        ),
    ]
