# Generated by Django 6.0 on 2025-12-06 20:41

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_index_to_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='updated at')),
                ('app_name', models.CharField(default='App name', help_text='Application name displayed across the app', max_length=100, verbose_name='application name')),
                ('hero_text', models.CharField(default='Your hero string', help_text='Tagline displayed on home screen and emails', max_length=255, verbose_name='hero text')),
                ('logo', models.ImageField(blank=True, help_text='Main logo (recommended: 512x512 PNG, max 2MB)', null=True, upload_to='branding/', verbose_name='logo')),
                ('logo_small', models.ImageField(blank=True, editable=False, help_text='Auto-generated small version (64x64)', null=True, upload_to='branding/', verbose_name='small logo')),
                ('primary_color', models.CharField(default='#667eea', help_text='Primary brand color (hex, e.g. #667eea)', max_length=7, validators=[apps.core.models.validate_hex_color], verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Secondary brand color (hex, e.g. #764ba2)', max_length=7, validators=[apps.core.models.validate_hex_color], verbose_name='secondary color')),
                ('contact_email', models.EmailField(default='support@example.com', help_text='Support contact email shown in app and emails', max_length=254, verbose_name='contact email')),
                ('support_url', models.URLField(blank=True, default='', help_text='Link to support page or documentation', verbose_name='support URL')),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
